
SET BUILDER_BIN_PATH=%1
SET QT_PLUGINS_SQLITECIPHER_PATH=%2
SET PLUGIN_NAME=%3

echo %RUN_TYPE%
echo %BUILDER_BIN_PATH%
echo %QT_PLUGINS_SQLITECIPHER_PATH%
echo %PLUGIN_NAME%

copy /y %BUILDER_BIN_PATH%\%PLUGIN_NAME%.dll %QT_PLUGINS_SQLITECIPHER_PATH%\%PLUGIN_NAME%.dll
copy /y %BUILDER_BIN_PATH%\%PLUGIN_NAME%d.dll %QT_PLUGINS_SQLITECIPHER_PATH%\%PLUGIN_NAME%d.dll
